### ISSUE TITLE
\jghostguarded with jlreq

### ISSUE THREAD

**Issue by minamotorin** [wtsnjp/BXghost#1]
Hi. Thanks for useful package.

I want to use this package with also jlreq.cls, but `\jghostguarded` doesn't work with it.

```latex
% This program is in the public domain.
\documentclass{jlreq}
%\documentclass[autodetect-engine,ja=standard]{bxjsarticle}
\usepackage{bxghost}
\begin{document}

aaaaa\jghostguarded{bbbbb}aaaaa

\end{document}
```

The cause is simply that `\xkanjiskip` is not inserted around `　` in jlreq.
Any ideas on how to use Japanese Ghost with jlreq?

I tried the following code and it *looks* work with jlreq.
But I'm not confident about metadata is correct.

```latex
% This program is in the public domain.
\documentclass{jlreq}
%\documentclass[autodetect-engine,ja=standard]{bxjsarticle}
\usepackage{bxghost}
\begin{document}
\newcommand{\myjghostguarded}[1]{%
  {\fontsize{0.00003}{0}\selectfont 阿\kern-0.00003pt}%
  #1%
  {\fontsize{0.00003}{0}\selectfont \kern-0.00003pt 阿}%
}

aaaaa\myjghostguarded{bbbbb}aaaaa

aaaaa\jghostguarded{bbbbb}aaaaa

\end{document}
```

Thanks.

**Comment by wtsnjp** [comment]
Thanks for the report. I have recognized the problem by reading the following article:

* [品詞記号出力マクロを設計しよう - TeX Alchemist Online](https://doratex.hatenablog.jp/entry/20211205/1638697391#upLaTeX--jlreqcls-%E3%81%AE%E5%A0%B4%E5%90%88)

A solution candidate:

* https://twitter.com/zr_tex8r/status/1467456386473000962

**Comment by minamotorin** [comment]
Thanks for fixing!
