### ISSUE TITLE
e-upTeXベースのpLaTeX対応

### ISSUE THREAD

**Issue by wtsnjp** [wtsnjp/BXghost#2]
何かしら修正が必要らしい。

cf. https://github.com/texjporg/tex-jp-build/issues/32#issuecomment-1427873967

**Comment by aminophen** [comment]
現状「\enablecjktoken というプリミティブがあれば upLaTeX」となっているところを「内部コードが Unicode (uptex) なら upLaTeX」に判定修正する必要があると思います。 https://github.com/aminophen/scsnowman/commit/d7e4321e2d7736835a9d4ba70057d02c3ea838dc みたいな感じでいいと思います。

**Comment by aminophen** [comment]
scsnowman でバグっていたので若干修正しました。

https://github.com/aminophen/scsnowman/blob/8d26c880cf15c4e1ffc75b6b51ce97d9e088216f/scsnowman.sty#L179-L189
